#!/bin/sh

set -e -x

spago build

case $1 in
    ccap)
        DB=dev15-db.wicourts.gov:5612:cc:viewer:somepassword
        ./get-schema.js --config $DB -d > samples/Domains.tmpl --purs-pkg Samples.Domains --scala-pkg samples.Domains
        ./get-schema.js --config $DB -t Case > samples/Case.tmpl --purs-pkg Samples.Case --scala-pkg samples.Case
        ;;
esac

for i in samples/*.tmpl; do
    # Attempts to compile the input.tmpl, reporting parsing errors if
    # not parsed correctly. NOTE: this passing does NOT guarantee a
    # working purescript or scala file on generation; for example, if
    # a type is undefined, no error checking catches this.
    ./codegen.js -m test $i

    # Pretty-print county.tmpl to the console. Removes comments and
    # puts the template in a readable format.
    ./codegen.js -m pretty $i

    # Generate the purescript file from the given template
    ./codegen.js -m purs $i

    # Generate the scala file from the given template
    ./codegen.js -m scala $i

    # TODO: Test compilation of generated output.
done

spago test
