-- This file is automatically generated. Do not edit.

module Test.Ccap.Codegen.FastDecoding.Domains where

import Ccap.Codegen.Runtime as R
import Data.Argonaut.Decode (class DecodeJson)
import Data.Argonaut.Encode (class EncodeJson)
import Data.Decimal (Decimal)
import Data.Generic.Rep (class Generic)
import Data.Show.Generic (genericShow)
import Data.Newtype (class Newtype)
import Prelude

newtype StringT = StringT String
derive instance newtypeStringT :: Newtype StringT _
instance encodeJsonStringT :: EncodeJson StringT where
  encodeJson a = jsonCodec_StringT.encode a
instance decodeJsonStringT :: DecodeJson StringT where
  decodeJson a = jsonCodec_StringT.decode a
derive instance eqStringT :: Eq StringT
derive instance ordStringT :: Ord StringT
derive instance genericStringT :: Generic StringT _
instance showStringT :: Show StringT where
  show a = genericShow a
jsonCodec_StringT :: R.JsonCodec StringT
jsonCodec_StringT =
  R.codec_newtype (R.jsonCodec_string)

newtype BooleanT = BooleanT Boolean
derive instance newtypeBooleanT :: Newtype BooleanT _
instance encodeJsonBooleanT :: EncodeJson BooleanT where
  encodeJson a = jsonCodec_BooleanT.encode a
instance decodeJsonBooleanT :: DecodeJson BooleanT where
  decodeJson a = jsonCodec_BooleanT.decode a
derive instance eqBooleanT :: Eq BooleanT
derive instance ordBooleanT :: Ord BooleanT
derive instance genericBooleanT :: Generic BooleanT _
instance showBooleanT :: Show BooleanT where
  show a = genericShow a
jsonCodec_BooleanT :: R.JsonCodec BooleanT
jsonCodec_BooleanT =
  R.codec_newtype (R.jsonCodec_boolean)

newtype IntT = IntT Int
derive instance newtypeIntT :: Newtype IntT _
instance encodeJsonIntT :: EncodeJson IntT where
  encodeJson a = jsonCodec_IntT.encode a
instance decodeJsonIntT :: DecodeJson IntT where
  decodeJson a = jsonCodec_IntT.decode a
derive instance eqIntT :: Eq IntT
derive instance ordIntT :: Ord IntT
derive instance genericIntT :: Generic IntT _
instance showIntT :: Show IntT where
  show a = genericShow a
jsonCodec_IntT :: R.JsonCodec IntT
jsonCodec_IntT =
  R.codec_newtype (R.jsonCodec_int)

newtype DecimalT = DecimalT Decimal
derive instance newtypeDecimalT :: Newtype DecimalT _
instance encodeJsonDecimalT :: EncodeJson DecimalT where
  encodeJson a = jsonCodec_DecimalT.encode a
instance decodeJsonDecimalT :: DecodeJson DecimalT where
  decodeJson a = jsonCodec_DecimalT.decode a
derive instance eqDecimalT :: Eq DecimalT
derive instance ordDecimalT :: Ord DecimalT
derive instance genericDecimalT :: Generic DecimalT _
instance showDecimalT :: Show DecimalT where
  show a = genericShow a
jsonCodec_DecimalT :: R.JsonCodec DecimalT
jsonCodec_DecimalT =
  R.codec_newtype (R.jsonCodec_decimal)
